# Generated by Django 4.2.6 on 2023-12-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
